name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: hello
        run: |
          echo "hello world"
      - name: run python script
        run: |
          pip install -r requirements.txt
          python ci.py